import type { Metadata } from "next";
import { Inter, Rubik } from "next/font/google";
import "./globals.css";
import Providers from "@/components/providers/Providers";
import Header from "@/components/layouts/Header";
import { cn } from "@/lib/utils";
import Layout from "@/components/layouts/Layout";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(rubik.className, "relative mx-auto flex flex-col")}>
        <Providers>
          <Header />
          <Layout className="flex-1">
            {children}
          </Layout>
        </Providers>
      </body>
    </html>
  );
}
